#!/usr/bin/env php 
<?php
$image = [
  'url'    => "https://github.com/mhitza/mhitza.github.io/assets/273079/35b66b53-700f-4490-86fe-a6a002f51640",
  'source' => "https://unsplash.com/photos/5ui0tfMC5ts",
  'author' => "Roberto Nickson"
];

$image_tmp = tempnam("/tmp", "image");
$out_tmp = tempnam("/tmp", "out") . ".txt";
file_put_contents($image_tmp, file_get_contents($image['url']));
exec("convert $image_tmp -resize 1x1 $out_tmp");
preg_match('/#[A-Z0-9]+/', file_get_contents($out_tmp), $matches);
$average_hex = $matches[0];

$entries = [];

foreach(scandir("references/", SCANDIR_SORT_DESCENDING) as $reference) {
  if (in_array($reference, [".", ".."])) {
    continue;
  }
  $lines = file("references/$reference");
  $entries[] = [
    'title'   => trim(substr($lines[0], 6)),
    'url'     => trim(substr($lines[1], 4)),
    'summary' => trim(substr($lines[2], 8)),
  ];
}

ob_start();
?>
<!DOCTYPE html>
<html lang="en">
  <head lang="en">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
    <meta name="description" content="a blog of technical problems, programming examples and the quircks of running a Linux system" />
    <title>personal code attic</title>
    <link href="atom.xml" type="application/atom+xml" rel="alternate" title="Atom feed" />
    <meta name="theme-color" value="<?php echo $average_hex; ?>">
    <style type="text/css">
      @font-face {
        font-family: 'Lato';
        font-style: normal;
        font-weight: 400;
        font-display: swap;
        src: local('Lato Regular'), local('Lato-Regular'), url(https://fonts.gstatic.com/s/lato/v16/S6uyw4BMUTPHjx4wXg.woff2) format('woff2');
        unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
      }

      html, body {
        margin: 0 !important;
        padding: 0 !important;
        font-size: 18px;
        font-family: 'Lato', sans-serif;
      }

      @media only screen and (max-width: 800px) {
        html {
          height: 100%;
        }
        body {
          display: grid;
          grid-template-rows: 85% auto;
          height: 100%;
        }

        main {
          padding-top: 1rem;
          padding-bottom: 1rem;
          grid-row-start: 2;
          grid-column-start: 1;
        }

        aside {
          grid-row-start: 1;
          grid-column-start: 1;
          padding-bottom: 0.1rem;
        }
      }

      @media only screen and (min-width: 800px) {
        body {
          height: 100vh;
          overflow-y: hidden;
        }

        main {
          padding-top: 1rem;
          padding-bottom: 1rem;
          grid-column-start: 2;
          grid-row-start: 1;

          overflow: auto;
        }

        aside {
          padding-top: 1rem;
          grid-column-start: 1;
          grid-row-start: 1;
          max-height: 100%;
        }
      }

      @media only screen and (min-width: 800px) and (max-width: 1440px) {
        body {
          display: grid;
          grid-template-columns: 35% 65%;
        }
      }

      @media only screen and (min-width: 1440px) and (max-width: 1920px) {
        body {
          display: grid;
          grid-template-columns: 25% auto;
          font-size: 24px;
        }

        section {
          width: 960px;
        }
      }

      @media only screen and (min-width: 1920px) {
        body {
          display: grid;
          grid-template-columns: 480px auto;
          font-size: 24px;
        }

        section {
          width: 960px;
        }
      }

      article {
        margin-left: 1rem;
        margin-right: 1rem;
      }

      article a {
        outline: none;
      }

      article a h2 {
        text-decoration: underline;
      }

      article a, article a h2 {
        font-size: 1.5rem;
        font-weight: normal;
        margin-top: 0;
        margin-bottom: 0;
        display: inline-block;
      }

      article a:focus + p {
        display: block;
      }

      article a:focus h2::before {
        font-size: 1.45rem;
        margin-right: 0.2rem;
        content: '☞';
        /** the magic of css http://archive.vn/cCUEE */
        display: inline-block;
        color: black;
      }

      article a:hover + p {
        display: block;
      }

      article p {
        font-size: 1.0rem;
        text-align: justify;
        margin-top: 0;
        /* display: none; */
      }

      a {
        color: dodgerblue;
      }
      a:active, a:visited {
        color: purple;
      }

      aside {
        background-position: center;
        background-size: cover;

        display: flex;
        flex-flow: column;
        flex-direction: column;
        justify-content: flex-end;

        position: relative;
      }

      aside .tooltip {
        position: absolute;
        top: 1rem;
        right: 1rem;
        background-color: white;
        color: black;
        font-weight: bold;
        opacity: 75%;
        padding: 0.5rem;
        font-size: 0.7rem;
        border-radius: 2px;
      }
      .tooltip::after {
        content: " ";
        position: absolute;
        top: 50%;
        left: 100%; /* To the right of the tooltip */
        opacity: 75%;
        margin-top: -8px;
        border-width: 8px;
        border-style: solid;
        border-color: transparent transparent transparent white;
      }

      aside a, aside a:visited {
        color: white
      }

      .label {
        color: white;
        padding-left: 1rem;
        padding-right: 1rem;
        font-size: 0.7rem;
      }

      h1 {
        margin-top: 0;
        margin-bottom: 0.5rem;
        padding: 0.1rem 0.4rem 0.2rem 0.4rem;
        background-color: black;
        display: inline-block;
        font-size: 2rem;
      }

      .label span {
        background-color: black;
        padding: 0.1rem 0.4rem 0.2rem 0.4rem;
        margin: 0;
        line-height: 1.7rem;
        white-space: nowrap;
        font-size: 1rem;
      }

      .image_credit {
        padding-left: 1.2rem;
        margin-bottom: 0.5rem !important;
      }

      hr {
        width: 100%;
        border: 0;
        border-top: 1px dashed white;
      }
    </style>
  </head>

  <body>
    <main>
      <section>
        <?php foreach ($entries as $entry): ?>
          <article>
            <a href="<?php echo $entry['url']; ?>">
              <h2><?php echo $entry['title']; ?></h2>
            </a>
            <p><?php echo $entry["summary"]; ?></p>
          </article>
        <?php endforeach; ?>
      </section>
    </main>

    <!-- http://archive.vn/hmIbO -->
    <aside style="background-image: linear-gradient(rgba(0,0,0,.3), rgba(0,0,0,.3)), url('<?php echo $image['url']; ?>')">
      <span class="tooltip" style="display: none">
        &lt;TAB&gt; navigation
      </span>
      <div class="label">
        <h1>personal code attic</h1>
      </div>
      <div class="label">
        <span>technical problems</span>
        <span>programming examples</span>
        <span>quirks of running a Linux system</span>
      </div>
      <hr>

      <div class="label image_credit">
        image by <a href="<?php echo $image['source']; ?>"><?php echo $image['author']; ?></a>
      </div>
    </aside>
  </body>
</html>
<?php file_put_contents("index.html", ob_get_clean()); ?>
