name: Publish article
on:
  push:
    branches:
      - master
    paths: 
      - 'post/**'

jobs:
  upload:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack

    - name: Publish article
      run: |
        title=$(echo "${{ github.event.head_commit.message }}" | head -1)
        GIST_URL=$(./scripts/publish `pwd`/post ${{ secrets.GIST_API_TOKEN }} "$title")
        echo "::set-env name=GIST_URL::$GIST_URL"
        
    - name: Add article reference
      run: |
        filename=references/`date +%4Y-%m-%d`

        echo "title: ${{ github.event.head_commit.message }}" > $filename
        echo "url: $GIST_URL" >> $filename

        summary=$(echo "${{ github.event.head_commit.message }}" | sed '2d' | paste -sd " " -)
        echo "summary: $summary" >> $filename

        rm post/*

    - name: Rebuild index.html
      run: |
        ./scripts/generate-index
    
    - name: Commit changes
      uses: docker://cdssnc/auto-commit-github-action
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        args: AUTOCOMMIT published post [skip ci]
