name: Publish article
on:
  push:
    branches:
      - master
    paths: 
      - 'post/**'

jobs:
  upload:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack

    - name: Publish article
      run: |
        title=$(echo "${{ github.event.head_commit.message }}" | head -1)
        GIST_URL=$(gh gist create post/* --public -d "$title")
        echo "GIST_URL=$GIST_URL" >> $GITHUB_ENV
      env:
        GH_TOKEN: ${{ secrets.GIST_API_TOKEN }}
        
    - name: Add article reference
      run: |
        filename=references/`date +%4Y-%m-%d`

        title=$(echo "${{ github.event.head_commit.message }}" | head -1)
        echo "title: $title" > $filename
        echo "url: $GIST_URL" >> $filename

        summary=$(echo "${{ github.event.head_commit.message }}" | sed -e '2d' | paste -sd " " -)
        echo "summary: $summary" >> $filename

        rm post/*

    - name: Rebuild index.html
      run: |
        ./scripts/generate-index
    
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: AUTOCOMMIT published post [skip ci]
