name: Rebuild Index
on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Rebuild index.html
      run: ./scripts/generate-index && ./scripts/generate-atom
    
    - uses: EndBug/add-and-commit@v9
      with:
        message: AUTOCOMMIT rebuilt index [skip ci]
