name: Rebuild Index
on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack

    - name: Rebuild index.html
      run: ./scripts/generate-index
    
    - uses: EndBug/add-and-commit@v9
      with:
        message: AUTOCOMMIT rebuilt index [skip ci]
